---
version: '2'
# Configuration of the Cycloid stack
name: 'Magento'
canonical: 'stack-magento'
status: 'public'
description: |
  Used to deploy a Magento on X Amazon EC2 instances behind an ELB load balancer, using RDS database and ElasticCache.
keywords:
  - 'magento'
  - 'provider:aws'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-magento/master/icon.png
technologies:
  - technology: Debian
    version: 9.x
  - technology: mysql
    version: 5.x
  - technology: Nginx
    version: 1.1x
  - technology: Php
    version: 7.2
  - technology: Redis
    version: 5.x
  - technology: Magento
    version: 2.x

config:
  default:
    name: 'Default'
    description: 'Default pipeline usecase'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'

    # Configuration of ansible for provisionning
    ansible:
      magento:
        path: 'ansible/environments/front.yml.sample'
        destination: '($ project $)/ansible/($ environment $)-front.yml'

    # Configuration of terraform to setup the infrastructure
    terraform:
      magento:
        path: 'terraform/magento.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/magento.tf'
