---
default:
  pipeline:
    Repository:
      - name: "Git URI"
        description: "URI of the git repository where the code is located"
        widget: simple_text
        type: string
        default: git@github.com:my/repository.git
        key: code_git_repository
      - name: "Code branch"
        description: "the git branch where the code to build is located"
        key: code_git_branch
        widget: simple_text
        type: string
        default: master
      - name: "Code git private key"
        description: "the private key to use to clone the git repository"
        widget: cy_cred
        default: "((ssh_code.ssh_key))"
        required: true
        key: code_git_private_key
        type: string
      - name: "Code build context"
        description: "the path to the pom.xml"
        widget: simple_text
        type: string
        default: ./
        key: code_build_context
      - name: "Github registry"
        description: "the URL of the github registry to push the package"
        widget: simple_text
        type: string
        default: https://maven.pkg.github.com/
        required: true
        key: github_registry
      - name: "Github username"
        description: "the username to use to push the package"
        widget: cy_cred
        required: true
        type: string
        key: github_username
        default: "((github_registry.username))"
      - name: "Github password"
        description: "the password or token to use to push the package"
        widget: cy_cred
        type: string
        required: true
        key: github_password
        default: "((github_registry.password))"
    Cycloid:
      - name: "Stack branch"
        description: "Branch to use on the public stack Git repository"
        key: stack_git_branch
        widget: simple_text
        type: string
        default: master
