version: "2"
name: k8s-runner
canonical: stack-k8s-runner
author: Cycloid
description: |
  Used to manage resources deployed on a Kubernetes cluster with plain YAML manifests and/or terraform resources.
image: https://raw.githubusercontent.com/cycloid-community-catalog/stack-k8s-runner/master/icon.png
keywords:
- kubernetes
- eks
- gke
- onprem
- terraform
- provider:aws
- provider:gcp
- provider:scw
template: false
template_ignore: []
technologies:
- technology: Kubernetes
  version: n/a
dependencies: []
config:
  default:
    cloud_provider: kubernetes
    description: For on-premises style Kubernetes clusters.
    name: Classic Kubernetes
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .project $)/pipeline/variables-($ .environment $).yml
        path: pipeline/variables.sample.yml
  default_terraform:
    cloud_provider: kubernetes
    description: For on-premises style Kubernetes clusters + terraform code.
    name: Classic Kubernetes + Terraform
    pipeline:
      pipeline:
        path: pipeline/pipeline-terraform.yml
      variables:
        destination: ($ .project $)/pipeline/variables-($ .environment $).yml
        path: pipeline/variables.sample.yml
  eks:
    cloud_provider: aws
    description: For AWS Elastic Kubernetes Service clusters.
    name: Amazon EKS
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .project $)/pipeline/variables-($ .environment $).yml
        path: pipeline/variables.sample.yml
  eks_terraform:
    cloud_provider: aws
    description: For AWS Elastic Kubernetes Service clusters + terraform code.
    name: Amazon EKS + Terraform
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .project $)/pipeline/variables-($ .environment $).yml
        path: pipeline/variables.sample.yml
  gke:
    cloud_provider: google
    description: For Google Kubernetes Engine clusters.
    name: Google GKE
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .project $)/pipeline/variables-($ .environment $).yml
        path: pipeline/variables.sample.yml
  gke_terraform:
    cloud_provider: google
    description: For Google Kubernetes Engine clusters + terraform code.
    name: Google GKE + Terraform
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .project $)/pipeline/variables-($ .environment $).yml
        path: pipeline/variables.sample.yml
