---

# Install boto required by the deployment role to get releases from s3
- name: install python-setuptools
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - python-setuptools
    - cron

- name: Install pip
  easy_install:
    name: pip
    state: latest

- name: Install boto packages
  pip:
    name: "{{item}}"
  with_items:
    - boto
    - boto3
