---
# Configuration of the Cycloid stack
name: 'Cycloid Infrastructure'
canonical: 'stack-infrastructure'
status: 'private'
description: |
  This stack will create Amazon vpc, a bastion ec2 server and various components you might require to deploy other stacks in production.
  This stack is currently a bundle of common usecase of our customers.
keywords:
  - 'infrastructure'
  - 'vpc'
  - 's3'
  - 'bastion'
  - 'ses'
  - 'deployment'
  - 'provider:aws'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-infrastructure/master/icon.png
technologies:
  - technology: Amazon VPC
    version: n/a
  - technology: Amazon S3 bucket
    version: n/a
  - technology: Amazon EC2 bastion
    version: n/a
  - technology: Amazon SES
    version: n/a
  - technology: Amazon IAM
    version: n/a

config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'
      destination: '($ project $)/pipeline/variables-($ environment $).yml'

  # Configuration of ansible for provisionning
  ansible:
    bastion:
      path: 'ansible/environments/bastion.yml.sample'
      destination: '($ project $)/ansible/environments/($ environment $)-bastion.yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    infrastructure:
      path: 'terraform/infrastructure.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/infrastructure.tf'
