---
shared:
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    run:
      path: /usr/bin/merge-stack-and-config
    outputs:
      - name: merged-stack
        path: "merged-stack"

resources:

  - name: git_stack
    type: git
    check_every: 2m
    source:
      uri: https://github.com/cycloid-community-catalog/stack-github-packages
      branch: ((stack_git_branch))
      paths:
        - maven/*

  - name: git_code
    type: git
    check_every: 2m
    source:
      uri: ((code_git_repository))
      branch: ((code_git_branch))
      private_key: ((code_git_private_key))
      paths:
        - ((code_build_context))/*

jobs:

  - name: build
    build_logs_to_retain: 3
    plan:
      - get: git_stack
        trigger: false
      - get: git_code
        trigger: true

      - task: merge-stack-and-config
        config:
          <<: *merge-stack-and-config
          inputs:
            - name: git_code
              path: "config"
            - name: git_stack
              path: "stack"
        params:
          CONFIG_PATH: ((code_build_context))
          STACK_PATH: maven

      - task: build
        file: merged-stack/.ci/build.yml
        privileged: true
        params:
          REGISTRY: ((github_registry))
          USERNAME: ((github_username))
          TOKEN: ((github_password))
          BUILD_CONTEXT: ((code_build_context))
