groups:

- name: overview
  jobs:
  - kubernetes-plan
  - kubernetes-apply
  - terraform-plan
  - terraform-apply

- name: kubernetes
  jobs:
  - kubernetes-plan
  - kubernetes-apply

- name: terraform
  jobs:
  - terraform-plan
  - terraform-apply

- name: destroy
  jobs:
  - kubernetes-delete
  - terraform-destroy

resource_types:

- name: kubernetes
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: ((k8s_version))

- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: ((terraform_version))

resources:

- name: git_config-k8s
  type: git
  icon: git
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((k8s_path))

- name: k8s
  type: kubernetes
  icon: kubernetes
  source:
    kubeconfig: ((k8s_kubeconfig))
    gcp_credentials_json: ((gcp_credentials_json))

- name: tfstate
  type: terraform
  icon: terraform
  source:
    env_name: ((env))
    private_key: ((terraform_modules_private_key))
    backend_type: gcs
    backend_config:
      bucket: ((terraform_storage_bucket_name))
      prefix: ((project))/((env))
      credentials: ((gcp_credentials_json))
    vars:
      kubeconfig: ((k8s_kubeconfig))
      gcp_project: ((gcp_project))
      gcp_region: ((gcp_region))
      env: ((env))
      project: ((project))
      customer: ((customer))
    env:
      GOOGLE_PROJECT: ((gcp_project))
      GOOGLE_REGION: ((gcp_region))
      GOOGLE_CREDENTIALS: ((gcp_credentials_json))
  
- name: git_config-terraform
  type: git
  icon: git
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((terraform_path))

jobs:

#
# Kubernetes
#
- name: kubernetes-plan
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-k8s
        trigger: true

      - task: download gcloud
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              tag: latest
          run:
            path: sh
            args:
              - '-exc'
              - |
                apk add -q --no-cache --no-progress bash curl python which
                curl -sSL https://sdk.cloud.google.com > install.sh
                bash install.sh --disable-prompts --install-dir=./gcloud
          outputs:
            - name: gcloud

      - try:
          put: kubectl diff
          resource: k8s
          params:
            kubectl: |
              diff $(grep -rnw git_config-k8s/((k8s_path)) -e 'apiVersion:' --include='*.yaml' --include='*.yml' --files-with-matches | xargs -I % sh -c "echo -f %" )

      - put: kubectl apply dry-run
        resource: k8s
        params:
          kubectl: |
            apply --dry-run=server $(grep -rnw git_config-k8s/((k8s_path)) -e 'apiVersion:' --include='*.yaml' --include='*.yml' --files-with-matches | xargs -I % sh -c "echo -f %" )
          wait_until_ready_selector: ((k8s_wait_ready_selector))

- name: kubernetes-apply
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-k8s
        trigger: false
        passed:
          - kubernetes-plan

      - put: kubectl apply
        resource: k8s
        params:
          kubectl: |
            apply $(grep -rnw git_config-k8s/((k8s_path)) -e 'apiVersion:' --include='*.yaml' --include='*.yml' --files-with-matches | xargs -I % sh -c "echo -f %" )
          wait_until_ready_selector: ((k8s_wait_ready_selector))

- name: kubernetes-delete
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-k8s
        trigger: false

      - put: kubectl delete
        resource: k8s
        params:
          kubectl: |
            delete $(grep -rnw git_config-k8s/((k8s_path)) -e 'apiVersion:' --include='*.yaml' --include='*.yml' --files-with-matches | xargs -I % sh -c "echo -f %" )
          wait_until_ready_selector: ((k8s_wait_ready_selector))

#
# Terraform
#
- name: terraform-plan
  serial: True
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-terraform
        trigger: true

      - put: tfstate
        params:
          plan_only: true
          terraform_source: git_config-terraform/((terraform_path))/

- name: terraform-apply
  serial: True
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - in_parallel:
      - get: git_config-terraform
        trigger: false
        passed:
          - terraform-plan
      - get: tfstate
        trigger: false
        passed:
          - terraform-plan

    - put: tfstate
      params:
        plan_run: true
        terraform_source: git_config-terraform/((terraform_path))/

- name: terraform-destroy
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
        - get: git_config-terraform
          trigger: false

        - put: tfstate
          params:
            action: destroy
            terraform_source: git_config-terraform/((terraform_path))/
          get_params:
            action: destroy
