{
 "title": "Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "300s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Prometheus Resident Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\",instance=\"localhost:9090\"}"
    }
   ]
  },
  {
   "title": "Prometheus CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Cores/s" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job='prometheus',instance='localhost:9090'}[5m])"
    }
   ]
  },
  { "title": "Scapes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Target Scrapes interval - Actual intervals between scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  {
   "title": "Scrape duration seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (scrape_duration_seconds)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "target sync - Actual interval to sync the scrape pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_sync_length_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Rule evaluation duration - The duration for a rule to execute.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Notifications sent per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_notifications_sent_total[2m])",
     "legendFormat": "{{alertmanager}}"
    },
    {
     "expr": "rate(alertmanager_notifications_total[2m])"
    }
   ]
  },
  {
   "title": "Alertmanager - The total number of alerts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(alertmanager_alerts_received_total[2m])",
     "legendFormat": "received - {{status}} - {{job}}"
    },
    {
     "expr": "rate(alertmanager_alerts_invalid_total[2m])",
     "legendFormat": "invalid - {{job}}"
    }
   ]
  }
 ]
}