# YAML anchors
shared:

  # Task : sync and merge with rsync 2 rep. Used to merge stack and config
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    run:
      path: /usr/bin/merge-stack-and-config
    outputs:
    - name: merged-stack
      path: "merged-stack"

groups:
- name: infra
  jobs:
  - terraform-plan
  - terraform-apply

- name: website
  jobs:
  - website-deploy
  - website-cache-invalidation

- name: destroy
  jobs:
  - terraform-destroy

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: ((terraform_version))

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: tfstate
  type: terraform
  icon: terraform
  source:
    env_name: ((project))-((env))
    backend_type: s3
    backend_config:
      bucket: ((terraform_storage_bucket_name))
      key: ((project))-((env)).tfstate
      workspace_key_prefix: ((project))
      region: ((aws_default_region))
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
    vars:
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
      env: ((env))
      project: ((project))
      customer: ((customer))
      aws_region: ((aws_default_region))
    env:
      AWS_ACCESS_KEY_ID: ((aws_access_key))
      AWS_DEFAULT_REGION: ((aws_default_region))
      AWS_SECRET_ACCESS_KEY: ((aws_secret_key))

- name: git-stack-terraform
  icon: github-circle
  type: git
  source:
    uri: https://github.com/cycloid-community-catalog/stack-static-website
    branch: ((stack_git_branch))
    path: /terraform/*

# The Pipeline stack (will be merged with the config)
- name: git-stack-pipeline
  icon: github-circle
  type: git
  source:
    uri: https://github.com/cycloid-community-catalog/stack-static-website
    branch: ((stack_git_branch))
    paths:
      - pipeline/*

- name: git-config-terraform
  icon: github-circle
  type: git
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    path: ((config_terraform_path))

- name: git-config-pipeline
  icon: github-circle
  type: git
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    path: ((config_pipeline_path))

- name: git-website
  icon: github-circle
  type: git
  source:
    uri: ((website_git_repository))
    branch: ((website_git_branch))
    private_key: ((website_git_private_key))

jobs:
  - name: terraform-plan
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - do:
        - get: git-stack-terraform
          trigger: true
        - get: git-config-terraform
          trigger: true

        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: git-config-terraform
              path: "config"
            - name: git-stack-terraform
              path: "stack"
          params:
            CONFIG_PATH: ((config_terraform_path))
            STACK_PATH: terraform

        - put: tfstate
          params:
            plan_only: true
            terraform_source: merged-stack/


  - name: terraform-apply
    build_logs_to_retain: 10
    plan:
      - do:
        # Trigger false because of manual approval
        - get: git-stack-terraform
          trigger: false
          passed:
            - terraform-plan
        - get: git-config-terraform
          trigger: false
          passed:
            - terraform-plan
        - get: tfstate
          trigger: false
          passed:
            - terraform-plan

        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: git-config-terraform
              path: "config"
            - name: git-stack-terraform
              path: "stack"
          params:
            CONFIG_PATH: ((config_terraform_path))
            STACK_PATH: terraform

        - put: tfstate
          params:
            plan_run: true
            terraform_source: merged-stack/

  - name: terraform-destroy
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - do:
          - get: git-stack-terraform
            trigger: false
          - get: git-config-terraform
            trigger: false
          - task: merge-stack-and-config
            config:
              <<: *merge-stack-and-config
              inputs:
              - name: git-config-terraform
                path: "config"
              - name: git-stack-terraform
                path: "stack"
            params:
              CONFIG_PATH: ((config_terraform_path))
              STACK_PATH: terraform

          - put: tfstate
            params:
              action: destroy
              terraform_source: merged-stack/
            get_params:
              action: destroy




  #
  # Build / Deploy / Invalidate
  #
  - name: website-deploy
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: tfstate
        trigger: false
        passed:
          - terraform-apply
      - get: git-website
        params: {depth: 1}
        trigger: true
      - get: git-config-pipeline
        params: {depth: 1}
        trigger: false
      - get: git-stack-pipeline
        params: {depth: 1}
        trigger: false

      - task: merge-stack-and-config
        config:
          <<: *merge-stack-and-config
          inputs:
          - name: git-config-pipeline
            path: "config"
          - name: git-stack-pipeline
            path: "stack"
        params:
          CONFIG_PATH: ((config_pipeline_path))
          STACK_PATH: pipeline

      - task: build-release
        file: merged-stack/build-release.yml

      - task: deploy-release
        file: merged-stack/deploy-release.yml
        params:
          BUCKET_REGION: ((aws_default_region))
          AWS_ACCESS_KEY_ID: ((aws_access_key))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
  - name: website-cache-invalidation
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: tfstate
        trigger: false
        passed:
          - terraform-apply
      - get: git-website
        passed:
          - website-deploy
        params: {depth: 1}
        trigger: true

      - task: cloudfront-invalidation
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -xc
            - |
              CLOUDFRONT=$(jq -r .cf_id tfstate/metadata)
              aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT} --paths '/*'
          params:
            AWS_ACCESS_KEY_ID: ((aws_access_key))
            AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
          inputs:
          - name: tfstate
