version: "2"
name: my-foo-stack
canonical: my-foo-stack
author: Adam Wardecki
status: private
description: dasd
image: ""
keywords:
- das
- provider:aws
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
