---
# Configuration of the Cycloid stack
name: 'Google GKE'
canonical: 'stack-gke'
status: 'public'
description: |
  Used to deploy an Google Kubernetes Engine cluster with one or more node pools.
keywords:
  - 'kubernetes'
  - 'gke'
  - 'provider:gcp'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-gke/master/icon.png
technologies:
  - technology: Google Kubernetes Engine
    version: latest
  - technology: Container-Optimized OS
    version: latest

config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'
      destination: '($ project $)/pipeline/variables-($ environment $).yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    gke:
      path: 'terraform/gke.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/gke.tf'
