---
# Configuration of the Cycloid stack
version: '4'
name: 'Terraform runner'
canonical: 'stack-terraform-runner'
description: |
  Allow you to do simple terraform actions: plan, create, destroy.
keywords:
  - 'terraform-runner'
  - 'terraform'
  - 'provider:aws'
  - 'provider:gcp'
  - 'provider:azure'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-terraform-runner/master/icon.png
technologies:
  - technology: terraform
    version: n/a

config:
  default:
    name: 'AWS'
    description: 'Using AWS S3 terraform backend.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
  gcp:
    name: 'GCP'
    description: 'Using Google GCS terraform backend.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
  azure:
    name: 'Azure'
    description: 'Using AzureRM terraform backend.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
