use_cases:

- name: cycloid-common
  sections:
  - name: Terraform
    groups:
    - name: "Source code"
      technologies: [pipeline]
      vars:
      - name: "Code git URL"
        description: "URL to the Git repository containing terraform source code."
        key: git_repository
        widget: simple_text
        type: string
        default: "git@github.com:MyUser/code.git"
      - name: "Code git branch"
        description: "Branch of the terraform source code Git repository."
        key: git_branch
        widget: simple_text
        type: string
        default: "master"
      - name: "Code git key"
        description: "SSH key pair to fetch terraform source code Git repository."
        key: git_private_key
        type: string
        widget: cy_cred
        widget_config:
          cred_types:
            - ssh
        default: "((($ .config_repository_credential_path $).ssh_key))"
      - name: "Code terraform path"
        description: "Path of Terraform files in the git repository."
        key: git_terraform_path
        widget: simple_text
        type: string
        default: "./"

    - name: "Configuration"
      technologies: [pipeline]
      vars:
      - name: "Private module SSH key"
        description: "SSH key used to clone private terraform modules from Git."
        key: terraform_modules_private_key
        widget: cy_cred
        type: string
        default: ""
      - name: "Terraform version"
        description: "terraform version used to execute your code."
        key: terraform_version
        widget: simple_text
        type: string
        default: "1.10.5"

- name: default
  sections:
  - name: Terraform
    groups:
    - name: "Cloud access"
      technologies: [pipeline]
      vars:

      - name: "Aws region"
        key: aws_default_region
        type: string
        widget: auto_complete
        values: ["eu-north-1", "ap-south-1", "eu-west-3", "eu-west-2", "eu-west-1", "ap-northeast-2", "ap-northeast-1", "sa-east-1", "ca-central-1", "ap-southeast-1", "ap-southeast-2", "eu-central-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"]
        default: "eu-west-1"
      - name: "AWS access key"
        description: "AWS access key which should be used"
        key: aws_cred
        type: string
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types: [aws]
        default: "((aws))"


- name: azure
  sections:
  - name: Terraform
    groups:
    - name: "Cloud access"
      technologies: [pipeline]
      vars:
      - name: "Azure environment"
        description: "The Cloud Environment which should be used"
        key: azure_env
        type: string
        widget: radios
        values: ["public", "china", "german", "stack", "usgovernment"]
        default: "public"
      - name: "Azure credential"
        description: "The azure credential containing subscription_id, tenant_id, client_id, client_secret"
        key: azure_cred
        type: string
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types: [azure]
        default: "((azure))"

- name: gcp
  sections:
  - name: Terraform
    groups:
    - name: "Cloud access"
      technologies: [pipeline]
      vars:
      - name: "GCP project name"
        description: "The GCP project name to use"
        key: gcp_project
        type: string
        widget: simple_text
        default: ($ .project $)
      - name: "GCP zone"
        key: gcp_zone
        type: string
        widget: auto_complete
        values: ["asia-east1-a", "asia-east1-b", "asia-east1-c", "asia-east2-a", "asia-east2-b", "asia-east2-c", "asia-northeast1-a", "asia-northeast1-b", "asia-northeast1-c", "asia-northeast2-a", "asia-northeast2-b", "asia-northeast2-c", "asia-northeast3-a", "asia-northeast3-b", "asia-northeast3-c", "asia-south1-a", "asia-south1-b", "asia-south1-c", "asia-southeast1-a", "asia-southeast1-b", "asia-southeast1-c", "australia-southeast1-a", "australia-southeast1-b", "australia-southeast1-c", "europe-north1-a", "europe-north1-b", "europe-north1-c", "europe-west1-b", "europe-west1-c", "europe-west1-d", "europe-west2-a", "europe-west2-b", "europe-west2-c", "europe-west3-a", "europe-west3-b", "europe-west3-c", "europe-west4-a", "europe-west4-b", "europe-west4-c", "europe-west6-a", "europe-west6-b", "europe-west6-c", "northamerica-northeast1-a", "northamerica-northeast1-b", "northamerica-northeast1-c", "southamerica-east1-a", "southamerica-east1-b", "southamerica-east1-c", "us-central1-a", "us-central1-b", "us-central1-c", "us-central1-f", "us-east1-b", "us-east1-c", "us-east1-d", "us-east4-a", "us-east4-b", "us-east4-c", "us-west1-a", "us-west1-b", "us-west1-c", "us-west2-a", "us-west2-b", "us-west2-c", "us-west3-a", "us-west3-b", "us-west3-c", "us-west4-a", "us-west4-b", "us-west4-c"]
        default: "europe-west1-b"
      - name: "GCP json credentials"
        description: "GCP credentials in json format which should be used"
        key: gcp_credentials_json
        type: string
        widget: cy_cred
        widget_config:
          cred_types: [gcp]
        default: "((gcp.json_key))"
