# Configuration of the CI pipeline
version: '2'
name: 'Amazon requirements'
canonical: 'aws-requirements'
status: 'public'
description: 'Create optionnaly an S3 bucket for terraform, IAM user as admin and codecommit repository.'
keywords:
  - 's3'
  - 'iam'
  - 'codecommit'
  - 'aws'
  - 'terraform'
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/infra-amazon-req/master/icon.png'
type: 'infra'
technologies:
  - technology: terraform
    version: n/a
  - technology: Amazon s3
    version: n/a
  - technology: Amazon codecommit
    version: n/a
config:
  default:
    name: 'Default'
    description: 'Default pipeline usecase'
    # Configuration of the CI pipeline
    pipeline:
      pipeline:
        path: 'pipeline/req.yml'
      variables:
        path: 'pipeline/variables.yml.sample'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'

    # Configuration of terraform to setup the infrastructure
    terraform:
      req:
        path: 'terraform/req.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/req.tf'

