---
version: "2"
use_cases:
- name: cycloid-common
  sections:
  - name: Cycloid Worker
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Disk size"
        unit: Go
        description: "Disk size for the instance."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 30
        values:
            - 30
            - 250
        required: true
    - name: SSH Keypair to access new instances
      technologies: [pipeline]
      vars:
      - name: "Keypair public"
        description: "The public SSH key, for SSH access to newly-created instances."
        key: keypair_public
        widget: cy_cred
        type: string
        default: "((custom_keypair.ssh_pub))"
        required: false

    - name: Concourse integration
      technologies: [pipeline]
      vars:
      - name: "Team ID"
        description: "This parameter can be obtained in Cycloid console, by clicking on your profile picture at the top right corner, then organization settings, then use the value of the ci_team_member field."
        key: team_id
        widget: simple_text
        type: string
        default: ""
        required: true
      - name: "Worker Private Key"
        description: "Leave default value if the worker is intended to run for the current organization. Otherwise, add Cycloid-worker-keys.ssh_prv credentials of the target organization."
        key: worker_key
        widget: cy_cred
        type: string
        default: "((cycloid-worker-keys.ssh_prv))"
        required: true

  - name: Cycloid Configuration
    groups:
    - name: Cycloid API
      technologies: [pipeline]
      vars:
      - name: "API Key"
        description: "API key to grant access to Cycloid API."
        key: cycloid_api_key
        type: string
        widget: cy_cred
        default: "((cycloid-api-key.key))"
        required: true


- name: aws
  sections:
  - name: Cycloid Worker
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Instance type for the worker."
        key: vm_instance_type
        widget: slider_list
        type: string
        default: "t3a.small"
        values:
            - "t3a.small"
            - "t3a.medium"
            - "t3a.large"
        required: true

  - name: AWS Cloud Provider
    groups:
    - name: AWS Cloud Provider
      technologies: [pipeline]
      vars:
      - name: "AWS account"
        description: "The AWS account where to deploy the infrastructure."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
      - name: "AWS region"
        description: "Amazon AWS region where to deploy the infrastructure."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
        required: true


- name: azure
  sections:
  - name: Cycloid Worker
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Instance type for the worker."
        key: vm_instance_type
        widget: slider_list
        type: string
        default: "Standard_DS2_v2"
        values:
            - "Standard_DS1_v2"
            - "Standard_DS2_v2"
            - "Standard_DS3_v2"
        required: true

  - name: Azure Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure credentials"
        description: "The azure credential used to deploy the infrastructure. It contains subscription_id, tenant_id, client_id, and client_secret."
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true
    - name: Azure Infrastructure
      technologies: [terraform]
      vars:
      - name: "Azure location"
        description: "Azure location for Terraform."
        key: azure_location
        widget: auto_complete
        type: string
        values:
            - Australia Central
            - China East
            - China North
            - East Asia
            - East US
            - France Central
            - France South
            - North Europe
            - Southeast Asia
            - South Africa North
            - South Africa West
            - West Europe
            - West US
        default: "West Europe"
        required: true
      - name: "Existing resource group name"
        description: "The name of the existing resource group where the resources will be deployed."
        key: rg_name
        widget: simple_text
        type: string
        default: ""
        required: true


- name: gcp
  sections:
  - name: Cycloid Worker
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Machine type"
        description: "Instance type for the worker."
        key: vm_machine_type
        widget: slider_list
        type: string
        default: "n2-standard-4"
        values:
            - n2-standard-2
            - n2-standard-4
            - n2-standard-8
        required: true

  - name: GCP Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "GCP project"
        description: "Google Cloud Platform project ID for Terraform."
        key: gcp_project
        widget: simple_text
        type: string
        default: "($ organization_canonical $)"
        required: true
      - name: "GCP region"
        description: "Google Cloud Platform region to use for Terraform."
        key: gcp_region
        widget: auto_complete
        type: string
        default: "europe-west1"
        values:
            - europe-west1
            - europe-west2
        required: true
      - name: "GCP zone"
        description: "Google Cloud Platform zone to use for Terraform. Make sure the zone extension exists for the selected region."
        key: gcp_zone
        widget: dropdown
        type: string
        default: "b"
        values:
            - a
            - b
            - c
            - d
            - e
            - f
        required: true      
      - name: "GCP credentials"
        description: "Google Cloud Platform JSON credentials to use for Terraform."
        key: gcp_credentials_json
        widget: cy_cred
        type: string
        default: "((gcp.json_key))"
        required: true