---
vcenter-template:
  pipeline:
    VMware:
      - name: "vCenter admin username"
        description: "vCenter admin username for Terraform."
        key: vsphere_user
        widget: cy_cred
        type: string
        default: "((basic_auth_vsphere.username))"
        required: true
      - name: "vCenter admin password"
        description: "vCenter admin password for Terraform."
        key: vsphere_password
        widget: cy_cred
        type: string
        default: "((basic_auth_vsphere.password))"
        required: true
      - name: "vCenter server"
        description: "vCenter server (IP or FQDN) for Terraform. Ex: 192.168.0.1"
        key: vsphere_server
        widget: simple_text
        type: string
        default: ""
        required: true

    Terraform backend:
      - name: "AWS access key"
        description: "Amazon AWS access key for Terraform."
        key: aws_access_key
        widget: cy_cred
        type: string
        default: "((aws.access_key))"
      - name: "AWS secret key"
        description: "Amazon AWS secret key for Terraform."
        key: aws_secret_key
        widget: cy_cred
        type: string
        default: "((aws.secret_key))"
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
      - name: "Terraform storage bucket"
        description: "AWS S3 bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform-remote-state
        required: true

    Stack Configuration:
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com:MyUser/config.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_config.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        source: config_git_repository
        default: "master"
        required: true

  terraform:
    VM:
      - name: "Datacenter"
        description: "Datacenter where to create the virtual machine."
        key: vsphere_datacenter
        widget: simple_text
        type: string
        default: ""
        required: true
      - name: "Datastore"
        description: "Datastore where to create the virtual machine."
        key: vsphere_datastore
        widget: simple_text
        type: string
        default: ""
        required: true
      - name: "Cluster"
        description: "Cluster where the virtual machine will be located."
        key: vsphere_cluster
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Virtual machine template"
        description: "Virtual machine template."
        key: vsphere_template
        widget: auto_complete
        type: string
        default: ""
        required: true
      - name: "Network"
        description: "Network where the virtual machine will be located."
        key: vsphere_network
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Name"
        description: "Name of the virtual machine."
        key: vm_name
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Number of CPU"
        unit: vCPU
        description: "Number of vCPU allocated to the virtual machine."
        key: vm_cpu
        widget: slider_range
        type: integer
        default: 2
        values:
            - 1
            - 4
        required: true
      - name: "Memory allocated"
        unit: Mo
        description: "Memory allocated to the virtual machine."
        key: vm_memory
        widget: number
        type: integer
        default: 2048
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size allocated to the virtual machine."
        key: vm_disk_size
        widget: number
        type: integer
        default: 100
        required: true

vcenter-iso:
  pipeline:
    VMware:
      - name: "vCenter admin username"
        description: "vCenter admin username for Terraform."
        key: vsphere_user
        widget: cy_cred
        type: string
        default: "((basic_auth_vsphere.username))"
        required: true
      - name: "vCenter admin password"
        description: "vCenter admin password for Terraform."
        key: vsphere_password
        widget: cy_cred
        type: string
        default: "((basic_auth_vsphere.password))"
        required: true
      - name: "vCenter server"
        description: "vCenter server (IP or FQDN) for Terraform. Ex: 192.168.0.1"
        key: vsphere_server
        widget: simple_text
        type: string
        default: ""
        required: true

    Terraform backend:
      - name: "AWS access key"
        description: "Amazon AWS access key for Terraform."
        key: aws_access_key
        widget: cy_cred
        type: string
        default: "((aws.access_key))"
      - name: "AWS secret key"
        description: "Amazon AWS secret key for Terraform."
        key: aws_secret_key
        widget: cy_cred
        type: string
        default: "((aws.secret_key))"
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
      - name: "Terraform storage bucket"
        description: "AWS S3 bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform-remote-state
        required: true

    Stack Configuration:
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com::MyUser/config.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_config.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        source: config_git_repository
        default: "master"
        required: true

  terraform:
    VM:
      - name: "Datacenter"
        description: "Datacenter where the virtual machine will be located."
        key: vsphere_datacenter
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Datastore VM"
        description: "Datastore where the virtual machine will be located."
        key: vsphere_datastore
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Datastore ISO"
        description: "Datastore where the ISO file will be located."
        key: vsphere_datastore_iso
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Path to ISO file"
        description: "Path to ISO file needed to bootstrap the virtual machine. Ex: ISOs/debian.iso"
        key: vm_iso
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Cluster"
        description: "Cluster where the virtual machine will be located."
        key: vsphere_cluster
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Network"
        description: "Network where the virtual machine will be located."
        key: vsphere_network
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Name"
        description: "Name of the virtual machine."
        key: vm_name
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Number of CPU"
        unit: vCPU
        description: "Number of vCPU allocated to the virtual machine."
        key: vm_cpu
        widget: slider_range
        type: integer
        default: 2
        values:
            - 1
            - 4
        required: true
      - name: "Memory allocated"
        unit: Mo
        description: "Memory allocated to the virtual machine."
        key: vm_memory
        widget: number
        type: integer
        default: 2048
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size allocated to the virtual machine."
        key: vm_disk_size
        widget: number
        type: integer
        default: 100
        required: true

esxi-iso:
  pipeline:
    VMware ESXi:
      - name: "ESXi admin username"
        description: "ESXi admin username for Terraform."
        key: vsphere_user
        widget: cy_cred
        type: string
        default: "((basic_auth_vsphere.username))"
        required: true
      - name: "ESXi admin password"
        description: "ESXi admin password for Terraform."
        key: vsphere_password
        widget: cy_cred
        type: string
        default: "((basic_auth_vsphere.password))"
        required: true
      - name: "ESXi server"
        description: "ESXi server (IP or FQDN) for Terraform. Ex: 192.168.0.1"
        key: vsphere_server
        widget: simple_text
        type: string
        default: ""
        required: true

    Terraform backend:
      - name: "AWS access key"
        description: "Amazon AWS access key for Terraform."
        key: aws_access_key
        widget: cy_cred
        type: string
        default: "((aws.access_key))"
      - name: "AWS secret key"
        description: "Amazon AWS secret key for Terraform."
        key: aws_secret_key
        widget: cy_cred
        type: string
        default: "((aws.secret_key))"
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
      - name: "Terraform storage bucket"
        description: "AWS S3 bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform-remote-state
        required: true

    Stack Configuration:
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com::MyUser/config.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_config.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        source: config_git_repository
        default: "master"
        required: true

  terraform:
    VM:
      - name: "ESXi hostname"
        description: "Needed to find the default resource pool for ESXi connection."
        key: esxi_hostname
        widget: simple_text
        type: string
        default: ""
        required: true
      - name: "Datacenter"
        description: "Datacenter where the virtual machine will be located."
        key: vsphere_datacenter
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Datastore VM"
        description: "Datastore where the virtual machine will be located."
        key: vsphere_datastore
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Datastore ISO"
        description: "Datastore where the ISO file will be located."
        key: vsphere_datastore_iso
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Path to ISO file"
        description: "Path to ISO file needed to bootstrap the virtual machine. Ex: ISOs/debian.iso"
        key: vm_iso
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Network"
        description: "Network where the virtual machine will be located."
        key: vsphere_network
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Name"
        description: "Name of the virtual machine."
        key: vm_name
        widget: simple_text
        default: ""
        type: string
        required: true
      - name: "Number of CPU"
        unit: vCPU
        description: "Number of vCPU allocated to the virtual machine."
        key: vm_cpu
        widget: slider_range
        type: integer
        default: 2
        values:
            - 1
            - 4
        required: true
      - name: "Memory allocated"
        unit: Mo
        description: "Memory allocated to the virtual machine."
        key: vm_memory
        widget: number
        type: integer
        default: 2048
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size allocated to the virtual machine."
        key: vm_disk_size
        widget: number
        type: integer
        default: 100
        required: true