---
version: '2'
# Configuration of the Cycloid stack
name: 'Jenkins'
canonical: 'stack-jenkins'
status: 'public'
description: |
  Deploy a standalone Jenkins with Docker components on AWS EC2.
keywords:
  - 'jenkins'
  - 'docker'
  - 'provider:aws'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-jenkins/master/icon.png
technologies:
  - technology: debian
    version: 9.x
  - technology: docker
    version: n/a
  - technology: jenkins
    version: 2.215-slim

config:
  default:
    name: 'Default'
    description: 'Default pipeline usecase'
    # Configuration of the CI pipeline
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'

    # Configuration of ansible for provisionning
    ansible:
      jenkins:
        path: 'ansible/environments/jenkins.yml.sample'
        destination: '($ project $)/ansible/environments/($ environment $)-jenkins.yml'

    # Configuration of terraform to setup the infrastructure
    terraform:
      jenkins:
        path: 'terraform/jenkins.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/jenkins.tf'
