version: "2"
name: Test stack RP edited
canonical: test_stack_rp
author: robert_parkin
status: private
description: This is a test stack, it can be deleted
image: ""
keywords:
- test
- provider:azure
template: false
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      config:
        destination: ($ project $)/terraform/($ environment $)/config.tf
        path: terraform/default/config.tf.sample
      test_stack_rp:
        destination: ($ project $)/terraform/($ environment $)/test_stack_rp.tf
        path: terraform/default/test_stack_rp.tf.sample
