version: "2"
name: getting-started
canonical: stack-getting-started
author: Cycloid
description: |
  Getting started stack purpose is to ovver a easy to use Cycloid stack during onboarding process.
  This stack offer on multi cloud provider to create a default compute instance.
image: https://raw.githubusercontent.com/cycloid-community-catalog/stack-getting-started/master/icon.png
keywords:
- aws
- azure
- gcp
- instance
- compute
- easy
- onboarding
- provider:aws
- provider:azure
- provider:gcp
template: false
template_ignore: []
technologies:
- technology: AWS
  version: n/a
- technology: Azure
  version: n/a
- technology: GCP
  version: n/a
dependencies: []
config:
  aws:
    cloud_provider: aws
    description: Create an Elastic Compute Cloud (EC2)
    name: AWS
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .project $)/pipeline/($ .environment $)/variables.yml
        path: pipeline/variables.sample.yml
    terraform:
      config:
        destination: ($ .project $)/terraform/($ .environment $)/main.tf
        path: terraform/aws/main.tf.sample
  azure:
    cloud_provider: azurerm
    description: Create a Virtual Machines
    name: Azure
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .project $)/pipeline/($ .environment $)/variables.yml
        path: pipeline/variables.sample.yml
    terraform:
      config:
        destination: ($ .project $)/terraform/($ .environment $)/main.tf
        path: terraform/azure/main.tf.sample
  gcp:
    cloud_provider: google
    description: Create a Compute Engine
    name: GCP
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .project $)/pipeline/($ .environment $)/variables.yml
        path: pipeline/variables.sample.yml
    terraform:
      config:
        destination: ($ .project $)/terraform/($ .environment $)/main.tf
        path: terraform/gcp/main.tf.sample
