groups:
- name: overview
  jobs:
  - terraform-plan
  - terraform-apply

- name: destroy
  jobs:
  - terraform-destroy

resource_types:

- name: terraform
  type: docker-image
  source:
    repository: cycloid/terraform-resource
    tag: ((terraform_version))

resources:

- name: tfstate
  type: terraform
  icon: terraform
  source:
    env_name: ($ .environment $)
    private_key: ((terraform_modules_private_key))
($- if eq .use_case "aws-ec2" $)
    backend_type: s3
    backend_config:
      bucket: ((terraform_storage_bucket_name))
      key: ($ .project $)-($ .environment $).tfstate
      workspace_key_prefix: ($ .project $)
      region: ((aws_default_region))
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
      endpoint: ((terraform_s3_endpoint))
      skip_credentials_validation: ((terraform_s3_skip_credentials_validation))
      force_path_style: ((terraform_s3_force_path_style))
    vars:
      env: ($ .environment $)
      project: ($ .project $)
      customer: ($ .organization_canonical $)
    env:
      AWS_ACCESS_KEY_ID: ((aws_access_key))
      AWS_DEFAULT_REGION: ((aws_default_region))
      AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
($- else if eq .use_case "azure-linux" $)
    backend_type: azurerm
    backend_config:
      container_name: ((terraform_storage_container_name))
      key: ((terraform_storage_container_path))/((project))-((env)).tfstate
      resource_group_name: ((terraform_resource_group_name))
      storage_account_name: ((terraform_storage_account_name))
      access_key: ((terraform_storage_access_key))
    vars:
      azure_location: ((azure_location))
      azure_env: ((azure_env))
      azure_client_id: ((azure_client_id))
      azure_client_secret: ((azure_client_secret))
      azure_subscription_id: ((azure_subscription_id))
      azure_tenant_id: ((azure_tenant_id))
      env: ($ .environment $)
      project: ($ .project $)
      customer: ($ .organization_canonical $)
    env:
      ARM_CLIENT_ID: ((azure_client_id))
      ARM_CLIENT_SECRET: ((azure_client_secret))
      ARM_TENANT_ID: ((azure_tenant_id))
      ARM_SUBSCRIPTION_ID: ((azure_subscription_id))
($- else if eq .use_case "gcp-gce" $)
    backend_type: gcs
    backend_config:
      bucket: ((terraform_storage_bucket_name))
      prefix: ((project))/((env))
      credentials: ((gcp_credentials_json))
    vars:
      gcp_project: ((gcp_project))
      gcp_region: ((gcp_region))
      env: ($ .environment $)
      project: ($ .project $)
      customer: ($ .organization_canonical $)
    env:
      GOOGLE_PROJECT: ((gcp_project))
      GOOGLE_REGION: ((gcp_region))
      GOOGLE_CREDENTIALS: ((gcp_credentials_json))
($- end $)

- name: git_terraform
  type: git
  icon: git
  source:
    uri: ((git_repository))
    branch: ((git_branch))
    private_key: ((git_private_key))
    paths:
      - ((git_terraform_path))

jobs:

- name: terraform-plan
  serial: True
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_terraform
        trigger: true

      - put: tfstate
        params:
          plan_only: true
          terraform_source: git_terraform/((git_terraform_path))/

- name: terraform-apply
  serial: True
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_terraform
        trigger: false
        passed:
          - terraform-plan
      - get: tfstate
        trigger: false
        passed:
          - terraform-plan

      - put: tfstate
        params:
          plan_run: true
          terraform_source: git_terraform/((git_terraform_path))/

- name: terraform-destroy
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
        - get: git_terraform
          trigger: false

        - put: tfstate
          params:
            action: destroy
            terraform_source: git_terraform/((git_terraform_path))/
          get_params:
            action: destroy
