---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: cycloid/concourse-dind
    tag: latest
run:
  path: concourse-dind-entrypoint.sh
  args:
    - 'bash'
    - '-ec'
    - |
      source /opt/docker-utils.sh
      docker_load image/image.tar

      docker images | awk -F' ' '{print $1":"$2}' | tail -1 | tee image/name
      docker inspect $(cat image/name)
inputs:
- name: merged-stack
- name: image
params:
  REPOSITORY: image
  TAG: latest
