---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: cycloid/concourse-dind
    tag: latest
run:
  path: concourse-dind-entrypoint.sh
  args:
    - 'bash'
    - '-ec'
    - |
      source /opt/docker-utils.sh
      docker_load image/image.tar

      docker tag $(cat image/digest) ${REPOSITORY}:${TAG}
      docker images
      docker inspect ${REPOSITORY}:${TAG}
inputs:
- name: merged-stack
- name: image
params:
  REPOSITORY: image
  TAG: latest
