# Configuration of the CI pipeline
name: 'Cycloid hello world'
canonical: 'stack-hello-world'
status: 'public'
description: 'Hello world stack which deploy small components depending of the cloud provider'
keywords:
  - 'aws'
  - 'lambda'
  - 'demo'
  - 'gcp'
  - 'cloudfunction'
technologies:
  - technology: Aws Lambda
    version: n/a
  - technology: GCP Cloud Function
    version: n/a
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/stack-hello-world/master/icon.png'
type: 'stack'
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/aws.yml'
    variables:
      path: 'pipeline/aws-variables.sample.yml'
  # Configuration of terraform
  terraform:
    aws:
      path: 'terraform-aws/main.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/main.tf'
    gcp:
      path: 'terraform-gcp/main.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/main.tf'
