version: '4'
name: Double Stack with Cheese
canonical: double_stack_with_cheese
author: 'dan_danowski'
# Fill in the stack details.
description: 'The bare minimum files to build your stack from scratch.'
image: https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png
template: false
# Add use cases to the stack.
# See: https://docs.cycloid.io/manage/pipeline/multi-use-case.html#multiple-use-case
config:
  default:
    name: 'Default'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
