# YAML anchors
shared:
- &kubernetes
  name: Kubernetes
  groups:
  - name: Config
    technologies: [pipeline]
    vars:
    - name: "Kubernetes version"
      description: "Used to get the right version of kubectl."
      key: k8s_version
      widget: simple_text
      type: string
      default: "1.23"
    - name: "Kubeconfig Credential"
      description: "Kubeconfig to access the cluster"
      key: k8s_kubeconfig
      widget: cy_cred
      widget_config:
        display_keys: true
        cred_types:
          - custom
      type: string
      default: "((custom_kubeconfig))"
    - name: "Wait ready selector"
      description: "Used to tell the concourse kubernetes resource to wait for a certain label selector to be ready."
      key: k8s_wait_ready_selector
      widget: simple_text
      type: string
      default: ""

- &terraform
  name: Terraform
  groups:
  - name: Variables
    technologies: [pipeline]
    vars:
    - name: "Terraform Extra Variables"
      description: "Specify any extra variables that should be passed to the Terraform execution."
      key: terraform_extra_vars
      widget: text_area
      type: map
    - name: "Terraform version"
      key: terraform_version
      widget: simple_text
      type: string
      default: '1.10.0'

- &cloudprovider-eks
  name: Cloud access
  groups:
  - name: Access
    technologies: [pipeline]
    vars:
    - name: "AWS access key"
      description: "AWS access key which should be used"
      key: aws_access_key
      widget: cy_cred
      widget_config:
        display_keys: true
        cred_types:
          - aws
      type: string
      default: ""

    - name: "AWS secret key"
      description: "AWS secret key which should be used"
      key: aws_secret_key
      widget: cy_cred
      widget_config:
        display_keys: true
        cred_types:
          - aws
      type: string
      default: ""

- &cloudprovider-gke
  name: Cloud access
  groups:
  - name: Access
    technologies: [pipeline]
    vars:
    - name: "GCP json credentials"
      description: "GCP credentials in json format which should be used"
      key: gcp_credentials_json
      widget_config:
        cred_types:
          - gcp
      type: string
      widget: cy_cred
      default: "((gcp_step-by-step.json_key))"

use_cases:
- name: default
  sections:
  - *kubernetes

- name: default_terraform
  sections:
  - *kubernetes
  - *terraform

- name: eks
  sections:
  - *kubernetes
  - *cloudprovider-eks

- name: eks_terraform
  sections:
  - *kubernetes
  - *terraform
  - *cloudprovider-eks
  - name: Cloud access Region
    groups:
    - name: Region
      technologies: [pipeline]
      vars:
      - name: "Aws region"
        key: aws_default_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1

- name: gke
  sections:
  - *kubernetes
  - *cloudprovider-gke

- name: gke_terraform
  sections:
  - *kubernetes
  - *terraform
  - *cloudprovider-gke
  - name: Cloud access Region
    groups:
    - name: Region
      technologies: [pipeline]
      vars:
      - name: "GCP project name"
        description: "The GCP project name to use"
        key: gcp_project
        widget: simple_text
        type: string
        default: cycloid-demo
      - name: "GCP zone"
        key: gcp_zone
        widget: auto_complete
        type: string
        values: [asia-east1-a,asia-east1-b,asia-east1-c,asia-east2-a,asia-east2-b,asia-east2-c,asia-northeast1-a,asia-northeast1-b,asia-northeast1-c,asia-northeast2-a,asia-northeast2-b,asia-northeast2-c,asia-northeast3-a,asia-northeast3-b,asia-northeast3-c,asia-south1-a,asia-south1-b,asia-south1-c,asia-southeast1-a,asia-southeast1-b,asia-southeast1-c,australia-southeast1-a,australia-southeast1-b,australia-southeast1-c,europe-north1-a,europe-north1-b,europe-north1-c,europe-west1-b,europe-west1-c,europe-west1-d,europe-west2-a,europe-west2-b,europe-west2-c,europe-west3-a,europe-west3-b,europe-west3-c,europe-west4-a,europe-west4-b,europe-west4-c,europe-west6-a,europe-west6-b,europe-west6-c,northamerica-northeast1-a,northamerica-northeast1-b,northamerica-northeast1-c,southamerica-east1-a,southamerica-east1-b,southamerica-east1-c,us-central1-a,us-central1-b,us-central1-c,us-central1-f,us-east1-b,us-east1-c,us-east1-d,us-east4-a,us-east4-b,us-east4-c,us-west1-a,us-west1-b,us-west1-c,us-west2-a,us-west2-b,us-west2-c,us-west3-a,us-west3-b,us-west3-c,us-west4-a,us-west4-b,us-west4-c]
        default: "europe-west1-b"
