---
# Configuration of the Cycloid stack
name: 'Concourse Server'
canonical: 'stack-concourse-server'
status: 'public'
description: |
  Used to deploy a Concourse server (web+atc) on Amazon EC2 instance behind ALB/NLB load balancers, using PostgreSQL RDS database.
keywords:
  - 'concourse'
  - 'server'
  - 'ui'
  - 'atc'
  - 'postgresql'
  - 'provider:aws'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-concourse-server/master/icon.png
technologies:
  - technology: Amazon Auto Scaling Group
    version: n/a
  - technology: Amazon Application Loadbalancer
    version: n/a
  - technology: Debian
    version: 9.x
  - technology: Concourse
    version: 3.14.x
  - technology: PostgreSQL
    version: 9.5.x

config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'
      destination: '($ project $)/pipeline/variables-($ environment $).yml'

  # Configuration of ansible for provisionning
  ansible:
    concourse-server:
      path: 'ansible/environments/concourse-server.yml.sample'
      destination: '($ project $)/ansible/environments/($ environment $)-concourse-server.yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    concourse-server:
      path: 'terraform/concourse-server.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/concourse-server.tf'
