---

- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') | default(playbook_dir + '/molecule/default/molecule.yml') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Destroy Concourse keys generate containers
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - concourse-signing-key-generate
        - concourse-tsa-key-generate
        - concourse-worker-key-generate

    - name: Destroy molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        state: absent
        force_kill: "{{ item.force_kill | default(True) }}"
      with_items: "{{ molecule_yml.platforms }}"
