---

- name: Install dependencies
  hosts: instance
  gather_facts: false
  tasks:
    - name: Install apt dependencies
      apt:
        name:
          - net-tools
          - lsb-release
          - curl
          - procps
          - btrfs-progs
        state: present

    - name: Create udev dir for ebs-automatic-nvme-mapping
      file:
        path: /etc/udev/rules.d
        state: directory
        mode: 0755

    - name: Create a disk image
      command: dd if=/dev/zero of=/opt/xvdf.img bs=1M count=2200
      args:
        creates: /opt/xvdf.img

    # 7: major type loopback
    - name: Create device
      command: mknod /dev/xvdf -m0660 b 7 0
      args:
        creates: /dev/xvdf
      register: xvdf_loopback

    - name: xvdf dettach
      command: losetup --detach /dev/xvdf
      when: xvdf_loopback.changed
      ignore_errors: true

    - name: Loopback attach
      command: losetup /dev/xvdf /opt/xvdf.img
      when: xvdf_loopback.changed

    # for ext4 validation
    # - name: mkfs.ext4 xvdf
    #   command: "mkfs.ext4 -m0 -L ephemeral0 /dev/xvdf"

    - name: mkfs.btrfs xvdf
      filesystem:
        fstype: btrfs
        dev: /dev/xvdf
        opts: -L ephemeral0 -f
