---
default:
  pipeline:
    Terraform:
      - name: "AWS access key"
        description: "Amazon AWS access key for Terraform."
        key: aws_access_key
        widget: cy_cred
        type: string
        default: "((aws.access_key))"
      - name: "AWS secret key"
        description: "Amazon AWS secret key for Terraform."
        key: aws_secret_key
        widget: cy_cred
        type: string
        default: "((aws.secret_key))"
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_default_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
      - name: "Terraform storage bucket"
        description: "AWS S3 bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform-remote-state

    Repos:
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com:MyUser/config.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_config.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        description: "The branch used by the config repository"
        source: config_git_repository
        default: "master"
        required: true

  terraform:
    config:
      - name: "Cluster name"
        description: "SSH keypair name to use to deploy EC2 instances."
        key: module.config.cluster_name
        widget: simple_text
        type: string
        default: "($ project $)-($ environment $)"

    vpc:
      - name: "VPC CIDR"
        description: "The CIDR to use to create the VPC."
        key: vpc_cidr
        widget: simple_text
        type: string
        default: "10.8.0.0/16"
        required: true
      - name: "Private subnets"
        description: "The private subnets cidr for the VPC."
        key: private_subnets
        widget: text_area
        type: array
        default:
            - "10.8.0.0/24"
            - "10.8.2.0/24"
            - "10.8.4.0/24"
        required: true
      - name: "Public subnets"
        description: "The public subnets cidr for the VPC."
        key: public_subnets
        widget: text_area
        type: array
        default:
            - "10.8.1.0/24"
            - "10.8.3.0/24"
            - "10.8.5.0/24"
        required: true

    eks:
      - name: "Cluster version"
        description: "The kubernetes cluster version."
        key: cluster_version
        widget: simple_text
        type: string
        default: "1.16"
        required: true
      - name: "Kubernetes control plane allowed ips"
        description: "Allow Inbound IP CIDRs to access the Kubernetes API."
        key: control_plane_allowed_ips
        widget: text_area
        type: array
        default:
            - "0.0.0.0/0"

    eks-node:
      - name: "SSH keypair"
        description: "Name of an existing AWS SSH keypair to use to deploy EC2 instances."
        key: keypair_name
        widget: simple_text
        type: string
        default: "cycloid"
      - name: "Bastion security group"
        description: "Additionnal security group ID to assign to servers. Goal is to allow bastion server to connect on nodes port 22 (SSH). Make sure the bastion VPC is peered. @see example below in this file."
        key: bastion_sg_allow
        widget: simple_text
        type: string
        default: ""
      - name: "Metrics security group"
        description: "Additionnal security group ID to assign to servers. Goal is to allow monitoring server to query metrics. Make sure the prometheus VPC is peered. @see example below in this file."
        key: metrics_sg_allow
        widget: simple_text
        type: string
        default: ""
      - name: "Node group given name"
        description: "Node group given name."
        key: node_group_name
        widget: simple_text
        type: string
        default: "standard"
      - name: "Node type"
        description: "Type of instance to use for node servers."
        key: node_type
        widget: auto_complete
        type: string
        default: "c5.xlarge"
        required: true
        values:
            - "t3.medium"
            - "t3.large"
            - "t3.xlarge"
            - "t3.2xlarge"
            - "m5.large"
            - "m5.xlarge"
            - "m5.2xlarge"
            - "m5.4xlarge"
            - "m5.8xlarge"
            - "m5.12xlarge"
            - "c3.xlarge"
            - "c3.large"
            - "c3.2xlarge"
            - "c3.4xlarge"
            - "c5.large"
            - "c5.xlarge"
            - "c5.2xlarge"
            - "c5.4xlarge"
            - "c5.9xlarge"
            - "c5.12xlarge"
      - name: "Node EBS optimized"
        description: "Whether the Instance is EBS optimized or not, related to the instance type you choose."
        key: node_ebs_optimized
        widget: switch
        type: boolean
        default: true
      - name: "Node desired number"
        description: "Desired number of node servers."
        key: node_count
        widget: simple_text
        type: string
        default: "1"
        required: true
      - name: "Min nodes (ASG)"
        description: "Minimum number of node servers allowed in the Auto Scaling Group."
        key: node_asg_min_size
        widget: number
        type: integer
        default: 1
      - name: "Max nodes (ASG)"
        description: "Maximum number of node servers allowed in the Auto Scaling Group."
        key: node_asg_max_size
        widget: number
        type: integer
        default: 10
      - name: "Nodes disk size"
        unit: Go
        description: "EKS nodes root disk size."
        key: node_disk_size
        widget: slider_range
        type: integer
        default: 60
        values:
            - 30
            - 500
      - name: "Node profile"
        description: "EKS nodes profile, can be either `ondemand` or `spot`."
        key: node_launch_template_profile
        widget: radios
        type: string
        default: "ondemand"
        values:
             - "ondemand"
             - "spot"
      - name: "Spot price"
        description: "EKS nodes spot price when `node_market_type = spot`."
        key: node_spot_price
        widget: simple_text
        type: string
        default: "0.3"
      - name: "Enable Cluster Autoscaler"
        description: "Should be true to add Cluster Autoscaler ASG tags."
        key: node_enable_cluster_autoscaler_tags
        widget: switch
        type: boolean
        default: false
