---
role: jenkins

aws_default_region: "{{ lookup('env','AWS_DEFAULT_REGION') | default('eu-west-1')}}"
aws_access_key_id: "{{ lookup('env','AWS_ACCESS_KEY_ID') | default(omit)}}"
aws_secret_access_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') | default(omit)}}"

# geerlingguy.docker
docker_install_compose: false
docker_users: admin

# jenkins
jenkins_port: 80
jenkins_version: 2.60.3
