# YAML anchors
shared:

  # Task : sync and merge with rsync 2 rep. Used to merge stack and config
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    run:
      path: /usr/bin/merge-stack-and-config
    outputs:
    - name: merged-stack
      path: "merged-stack"

  # Task : connect on the bastion server and run ansible from it
  - &run-ansible-from-bastion
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cycloid/cycloid-toolkit
          tag: v((ansible_version))
      run:
        path: /usr/bin/ansible-runner
      caches:
        - path: ansible-playbook/roles
      inputs:
      - name: merged-stack
        path: ansible-playbook

groups:
- name: overview
  jobs:
  - build
  - full-deploy-front
  - app-deploy-front
  - terraform-plan
  - terraform-apply
  - functional-tests
- name: destroy
  jobs:
  - terraform-destroy

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: '1.0.4'

resources:
- name: tfstate
  type: terraform
  source:
    env_name: ((env))
    backend_type: s3
    backend_config:
      bucket: ((terraform_storage_bucket_name))
      key: ((project))-((env)).tfstate
      workspace_key_prefix: ((project))
      region: ((aws_default_region))
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
    vars:
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
      env: ((env))
      project: ((project))
      customer: ((customer))
      aws_region: ((aws_default_region))
      rds_password: ((rds_password))
    env:
      AWS_ACCESS_KEY_ID: ((aws_access_key))
      AWS_DEFAULT_REGION: ((aws_default_region))
      AWS_SECRET_ACCESS_KEY: ((aws_secret_key))

- name: s3_magento-release
  type: s3
  source:
    bucket: ((magento_deploy_bucket_name))
    versioned_file: ((magento_deploy_bucket_object_path))
    private: true
    region_name: ((aws_default_region))
    access_key_id: ((aws_access_key))
    secret_access_key: ((aws_secret_key))

- name: git_stack-ansible
  type: git
  source:
    uri: https://github.com/cycloid-community-catalog/stack-magento
    branch: ((stack_git_branch))
    paths:
      - ansible/*

# The Ansible config (will be merged with the stack)
- name: git_config-ansible
  type: git
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((config_ansible_path))/((env))-*


# The Terraform stack (will be merged with the config)
- name: git_stack-terraform
  type: git
  source:
    uri: https://github.com/cycloid-community-catalog/stack-magento
    branch: ((stack_git_branch))
    paths:
      - terraform/*

# The Terraform config (will be merged with the stack)
- name: git_config-terraform
  type: git
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((config_terraform_path))/*

- name: git_magento-code
  type: git
  source:
    uri: ((magento_git_repository))
    branch: ((magento_git_branch))
    private_key: ((magento_git_private_key))


jobs:
  - name: terraform-plan
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - do:
        - get: git_stack-terraform
          trigger: true
        - get: git_config-terraform
          trigger: true

        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: git_config-terraform
              path: "config"
            - name: git_stack-terraform
              path: "stack"
          params:
            CONFIG_PATH: ((config_terraform_path))
            STACK_PATH: terraform

        - put: tfstate
          params:
            plan_only: true
            terraform_source: merged-stack/

  - name: terraform-apply
    build_logs_to_retain: 10
    plan:
      - do:
        # Get the PR on the project #
        - get: git_stack-terraform
          trigger: false
          passed:
            - terraform-plan
        - get: git_config-terraform
          trigger: false
          passed:
            - terraform-plan
        - get: tfstate
          trigger: false
          passed:
            - terraform-plan

        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: git_config-terraform
              path: "config"
            - name: git_stack-terraform
              path: "stack"
          params:
            CONFIG_PATH: ((config_terraform_path))
            STACK_PATH: terraform

        - put: tfstate
          params:
            plan_run: true
            terraform_source: merged-stack/

  - name: terraform-destroy
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - do:
          - get: git_stack-terraform
            trigger: false
          - get: git_config-terraform
            trigger: false
          - task: merge-stack-and-config
            config:
              <<: *merge-stack-and-config
              inputs:
              - name: git_config-terraform
                path: "config"
              - name: git_stack-terraform
                path: "stack"
            params:
              CONFIG_PATH: ((config_terraform_path))
              STACK_PATH: terraform

          - put: tfstate
            params:
              action: destroy
              terraform_source: merged-stack/
            get_params:
              action: destroy

  - name: build
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_magento-code
        trigger: true

      - task: build-release
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/composer
              tag: php7.1
          run:
            path: /bin/bash
            args:
            - -xec
            - |
              DIR=${PWD}

              echo "### Build release"
              cd ${DIR}/code

              composer install --optimize-autoloader --ignore-platform-reqs

              php bin/magento module:enable --all

              php -d memory_limit=2048M bin/magento setup:di:compile -v

              echo "# create the archive release"
              cd ${DIR}
              tar --exclude code/.git -zcf ${PWD}/release/magento-release.tar.gz code
          # params:
          inputs:
          - name: git_magento-code
            path: code
          outputs:
          - name: release
            path: "release"
      - put: s3_magento-release
        params:
          acl: private
          file: release/magento-release.tar.gz

  - name: full-deploy-front
    build_logs_to_retain: 10
    plan:
    - do:

      - get: tfstate
        trigger: true
        passed:
          - terraform-apply

      - get: git_stack-ansible
        trigger: true
      - get: git_config-ansible
        trigger: true

      - get: s3_magento-release
        passed:
        - build
        trigger: false

      - get: git_magento-code
        trigger: false

      - task: merge-stack-and-config
        config:
          <<: *merge-stack-and-config
          inputs:
          - name: git_config-ansible
            path: "config"
          - name: git_stack-ansible
            path: "stack"
          - name: tfstate
            path: "terraform"
        params:
          CONFIG_PATH: ((config_ansible_path))
          STACK_PATH: ansible

      - task: run-ansible
        <<: *run-ansible-from-bastion
        params:
          BASTION_URL: ((bastion_url))
          BASTION_PRIVATE_KEY: ((bastion_private_key_pair))
          ANSIBLE_VAULT_PASSWORD: ((ansible_vault_password))
          ANSIBLE_PLAYBOOK_PATH: ansible-playbook
          ANSIBLE_PLAYBOOK_NAME: magento.yml
          AWS_DEFAULT_REGION: ((aws_default_region))
          AWS_ACCESS_KEY_ID: ((aws_access_key))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
          MAGENTO_DEPLOY_BUCKET_NAME: ((magento_deploy_bucket_name))
          MAGENTO_DEPLOY_BUCKET_OBJECT_PATH: ((magento_deploy_bucket_object_path))
          MAGENTO_DEPLOY_BUCKET_REGION: ((aws_default_region))
          ANSIBLE_FORCE_GALAXY: false
          EXTRA_VARS:
            customer: ((customer))
            project: ((project))
            env: ((env))
            default_ec2_region: ((aws_default_region))
            magento_admin_password: ((magento_admin_password))


  - name: app-deploy-front
    build_logs_to_retain: 10
    plan:
    - do:

      - get: git_stack-ansible
        trigger: false
        passed:
          - full-deploy-front

      - get: git_config-ansible
        trigger: false
        passed:
          - full-deploy-front

      - get: tfstate
        trigger: false
        passed:
          - full-deploy-front

      - get: s3_magento-release
        passed:
        - build
        trigger: true
      - get: git_magento-code
        trigger: false

      - task: merge-stack-and-config
        config:
          <<: *merge-stack-and-config
          inputs:
          - name: git_config-ansible
            path: "config"
          - name: git_stack-ansible
            path: "stack"
          - name: tfstate
            path: "terraform"
        params:
          CONFIG_PATH: ((config_ansible_path))
          STACK_PATH: ansible

      - task: run-ansible
        <<: *run-ansible-from-bastion
        params:
          BASTION_URL: ((bastion_url))
          BASTION_PRIVATE_KEY: ((bastion_private_key_pair))
          ANSIBLE_VAULT_PASSWORD: ((ansible_vault_password))
          ANSIBLE_PLAYBOOK_PATH: ansible-playbook
          ANSIBLE_PLAYBOOK_NAME: magento.yml
          AWS_DEFAULT_REGION: ((aws_default_region))
          AWS_ACCESS_KEY_ID: ((aws_access_key))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
          MAGENTO_DEPLOY_BUCKET_NAME: ((magento_deploy_bucket_name))
          MAGENTO_DEPLOY_BUCKET_OBJECT_PATH: ((magento_deploy_bucket_object_path))
          MAGENTO_DEPLOY_BUCKET_REGION: ((aws_default_region))
          ANSIBLE_FORCE_GALAXY: false
          EXTRA_VARS:
            customer: ((customer))
            project: ((project))
            env: ((env))
            default_ec2_region: ((aws_default_region))
            magento_admin_password: ((magento_admin_password))
          TAGS:
            - deploy

  - name: functional-tests
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: s3_magento-release
        trigger: true
        passed: [app-deploy-front]
      - get: git_magento-code
        passed: [app-deploy-front]
        trigger: false


      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/busybox
              tag: latest
          run:
            path: /bin/bash
            args:
            - -xec
            - |
              DIR=${PWD}
              echo "Dummy functional tests OK"
