---
version: '2'
# Configuration of the Cycloid stack
name: 'External worker'
canonical: 'stack-external-worker'
status: 'public'
description: |
  This stack will deploy an Amazon ASG with external workers for Cycloid.io.
keywords:
  - 'workers'
  - 'worker'
  - 'concourse'
  - 'external'
  - 'cycloid'
  - 'provider:aws'
  - 'provider:scw'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-external-worker/master/icon.png
technologies:
  - technology: Amazon Auto Scaling Group
    version: n/a
  - technology: concourse
    version: n/a

config:
  aws:
    name: 'AWS'
    description: 'Deployment on Amazon Web Services.'
    # Configuration of the CI pipeline
    pipeline:
      pipeline:
        path: 'pipeline/pipeline-aws.yml'
      variables:
        path: 'pipeline/variables-aws.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    # Configuration of ansible for provisionning
    ansible:
      external-worker:
        path: 'ansible/variables.yml.sample'
        destination: '($ project $)/ansible/($ environment $)-worker.yml'
    # Configuration of terraform to setup the infrastructure
    terraform:
      external-worker:
        path: 'terraform/aws/external-worker.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/external-worker.tf'

  scw:
    name: 'Scaleway'
    description: 'Deployment on Scaleway Elements.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline-scw.yml'
      variables:
        path: 'pipeline/variables-scw.yml'
    ansible:
      external-worker:
        path: 'ansible/variables.yml.sample'
        destination: '($ project $)/ansible/($ environment $)-worker.yml'
    terraform:
      external-worker:
        path: 'terraform/scw/external-worker.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/external-worker.tf'
